REM *** DAS Normal Login ***
Date 02-16-2008 : Time 12:46:50
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 12:50:51
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 12:50:53
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 12:52:59
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 12:57:37
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 12:57:53
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 12:58:32
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 12:58:34
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:03:28
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:04:03
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 13:04:07
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:04:21
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 13:04:24
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:05:29
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:06:00
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 13:06:02
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:06:19
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 13:06:22
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 13:29:50

REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:29:53
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:33:14
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 13:33:50

REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:33:57
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:36:43
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 13:37:35
Power Failure and UPS also under repair
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:37:37
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 13:37:40
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:50:45
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 13:51:11
Checking and Testing Software
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:51:14
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:51:37
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 13:52:13
TESTING
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 13:52:15
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 13:52:21
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 14:45:31
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 14:47:52
TESTING
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 14:48:04
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 14:48:18
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 14:51:16
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 14:51:47
TESTING
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 15:16:24
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 15:16:56
TESTING
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 15:18:38
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 15:19:32
TESTING
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 15:21:09
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 15:21:36
TESTING
REM *** DAS Improper ShutDown Reason ***
Date 02-16-2008 : Time 15:38:25
TEST
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 15:39:17
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 15:39:51
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 15:41:00
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 15:41:34
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 15:42:15
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 15:45:03
REM *** DAS Normal Login ***
Date 02-16-2008 : Time 15:51:33
REM *** DAS Normal ShutDown ***
Date 02-16-2008 : Time 15:53:12
REM *** DAS Improper ShutDown Reason ***
Date 02-17-2008 : Time 20:35:38
TESTING
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 20:36:29
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 20:36:37
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 20:37:32
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 20:37:48
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 20:38:43
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 20:40:41
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 20:45:24
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 20:46:35
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 20:47:34
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 20:48:01
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 20:51:17
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 20:51:23
REM *** DAS Improper ShutDown Reason ***
Date 02-17-2008 : Time 20:51:40
TEST
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 21:49:12
REM *** DAS Improper ShutDown Reason ***
Date 02-17-2008 : Time 21:49:42
TEST
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 21:50:08
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 21:50:20
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 21:50:35
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 21:50:43
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 21:55:38
REM *** DAS Improper ShutDown Reason ***
Date 02-17-2008 : Time 21:56:09
TEST
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 21:59:37
REM *** DAS Improper ShutDown Reason ***
Date 02-17-2008 : Time 22:00:09
UPS
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:00:11
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:04:55
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:14:15
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:15:47
REM *** DAS Improper ShutDown Reason ***
Date 02-17-2008 : Time 22:16:10
TEST
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:16:12
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:16:26
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:20:47
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:22:09
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:35:59
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:36:06
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:37:43
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:37:48
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:40:58
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:41:02
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:43:19
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:43:23
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:46:32
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:46:36
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:49:21
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:50:37
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 22:54:55
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 22:55:49
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 23:00:04
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 23:00:43
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 23:01:02
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 23:01:15
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 23:02:07
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 23:04:14
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 23:10:00
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 23:10:51
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 23:24:31
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 23:28:31
REM *** DAS Normal Login ***
Date 02-17-2008 : Time 23:52:59
REM *** DAS Normal ShutDown ***
Date 02-17-2008 : Time 23:53:24
REM *** DAS Improper ShutDown Reason ***
Date 02-18-2008 : Time 13:50:11
TEST
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 13:50:20
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 13:51:05
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 13:52:23
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 14:03:57
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 14:04:03
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 14:08:17
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 14:08:26
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 14:08:51
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 14:08:56
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 14:15:32
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 14:15:36
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 14:16:21
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 14:16:26
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 14:19:02
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 14:19:07
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 14:21:21
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 14:21:26
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 14:25:15
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 14:25:19
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 14:27:54
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 14:28:20
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 15:16:52
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 15:16:56
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 15:42:59
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 15:44:08
REM *** DAS Normal Login ***
Date 02-18-2008 : Time 16:10:32
REM *** DAS Improper ShutDown Reason ***
Date 02-18-2008 : Time 16:10:57
TEST
REM *** DAS Normal ShutDown ***
Date 02-18-2008 : Time 16:11:02
