CLOSE ALL
CLEAR ALL
CLEAR
SELECT 0
USE VAN ALIAS VAN
SELECT VAN
DELETE ALL FOR LEN(ALLTRIM(INV_IDY)) = 0
SELECT 0
USE SNV ALIAS SNV
SELECT SNV
DELETE ALL FOR LEN(ALLTRIM(INV_IDY)) = 0
CLOSE ALL
CLEAR
RETURN
